---
title: ""
editor: visual
---

# Conference participation

## 2024

-   Scientific Days 2024 of UMI SOURCE - at the Université Versailles Saint-Quentin-en-Yvelines, Guyancourt (France).

-   Conference Development Days of the Association Tiers Monde (ATM) / [Journées du développement de l'Association Tiers Monde (ATM) - May 2024](https://www.gemdev.org/33354) - organized at Condorcet, Aubervilliers (France).

-   [Workshop of the Inequalities Working Group (GT Inégalités)](https://www.gemdev.org/32975) of the French National Research Institute for Sustainable Developpement (IRD) - February 1-2, 2024 - organized at Condorcet, Aubervilliers (France).

## 2023

-   Doctoral Days "Critical Perspectives on Development" / "[Regards critiques sur le développement](#0)" - October 18-20, 2023  - organized by GEMDEV (Groupement pour l'étude de la mondialisation et du développement), Campus Condorcet, Aubervilliers (France).

-   Conference on Development Days of the Association Tiers Monde (ATM) / J[ournées du développement de l'Association Tiers Monde (ATM) - May 2023](https://www.bse.u-bordeaux.fr/xxxviiies-journees-du-developpement-de-lassociation-tiers-monde/) - organized by Bordeaux School of Economics (BSE), UMR CNRS 5319 Passages, Université of Bordeaux-Montaigne and Les Afriques dans le Monde (LAM) Sciences Po Bordeaux, France.

-   [SFREM](https://www.umi-source.uvsq.fr/semaine-formation-recherche-de-la-gs-economics-management) GS Economics & Management, Université Paris-Saclay - May 2023 - Université Jean Monnet, Sceaux.

-   Scientific Days 2023 of UMI SOURCE ([JUMI 2023](#0)) - at the Université Cheikh Anta Diop (UCAD), Dakar (Sénégal).

-   [MOMENTOM International Congress](https://momentom2023.sciencesconf.org/) - March 2023 - organized by the Institute of Sustainable Energy (IES) at ENS Paris-Saclay, France.

-   [Laboratory Seminar](https://www.umi-source.uvsq.fr/seminaire-umi-source-du-26-janvier-2022-intervention-de-alexandre-mathieu-doctorant-umi-source) - January 2023 - organized by UMI SOURCE, France.

## 2022

-   Conference on Overseas Economic Days ARUM / [Journées économiques des Outre-mer ARUM](https://www.umi-source.uvsq.fr/lumi-source-represente-au-colloque-arum-2022) - October 2022 - organized by the Economic, Social and Environmental Council of France - CESE (Conseil Économique, Social et Environnemental), Paris (France).

# Conference organization 

-   Organization and facilitation of the Open Science Days "From Data Management to Publication" / "[De la gestion des données à la publication](https://www.umi-source.uvsq.fr/journees-sciences-ouverte-2024)" - April 23-25, 2024 - *Université Félix Houphouët-Boigny and CIRES*, **Abidjan** (**Ivory Coast**).

-   Organization and facilitation of the [Scientific Days 2023 of UMI SOURCE](https://www.umi-source.uvsq.fr/les-journees-scientifiques-de-lumi-source-2023) - *Université Cheikh Anta Diop (UCAD)*, **Dakar** (**Senegal**).

-   Organization and facilitation of the mountly inter-antenna workshops (ateliers mensuels inter-antennes) between 2022 and 2024 for doctoral students from the units in **Ivory Coast**, **France**, **Madagascar**, and **Senegal** of UMI SOURCE.
