---
title: ""
editor: visual
---

## Grants

\[2\] [PSF CREONS](https://umisource.github.io/psf_creons/). Role: Co-PI. Budget: 30k€. Funder: French National Research Institute for Sustainable Development (IRD).

\[1\] PhD Scholarship (2021-), *Université Paris-Saclay, UVSQ*

## Research programs

\[4\] Training Project "towards an equitable and open research cooperative between North and South" / Projet de Formation Structurant vers une coopérative de recherche équitable et ouverte entre le Nord et le Sud ([PSF CREONS](https://umisource.github.io/psf_creons/)), financed by IRD.

\[3\] Co-development of a working group to explore a just transition in research.

\[2\] Working Group on Doctoral Disparities and Inequalities / [Groupe de travail sur les disparités et inégalités doctorales (GTDID)](https://www.umi-source.uvsq.fr/gt-disparites-et-inegalites-doctorale).

\[1\] Took part in the *POLIR* program ["POLICIES and Institutions in small island economies (SIE) for better resilience in response to the COVID crisis"](https://www.umi-source.uvsq.fr/projet-polir) (2020-2023).

## Consultancy

In december 2024, qualitative research on the mobilization of local resources by local authorities in Madagascar - Commissioner: Ministère de l'Europe et des Affaires étrangères (France).
